### ISSUE TITLE
Organizing topics in physics

### ISSUE THREAD

**Issue by firasm** [open-resources/learning_outcomes#1]
Hey @SteveCollins17,

As we discussed today, let's start with [this format](https://github.com/open-resources/learning_outcomes/blob/main/LOtemplate.md):

```
- Math (Area)
	- Algebra (topic)
		- 
	- Derivatives (topic)
		- Chain rule (sub-topic)
			- "Students will learn how to apply the chain rule to different questions."
			- "Sentence 2"
			- "Sentence"
			- 
			- 
		- Product rule
	- Integrals
		- 
	- System of equations
	- Quadratic formula
- Vectors
	- 
		- 
- Kinematics
	- 
		- 
- Force
	- 
		- 
- Energy
	- 
		- 
- Momentum
	- 
```

Let me know when you have the Areas and topics done, and then I can get some help for you to finish out the rest of it.

**Comment by firasm** [comment]
hey @SteveCollins17, thanks for getting started on this! 

I have updated the file you created with the following changes:
- changed file to .yml instead of .md
- renamed the file to `Masterlist_Topics_Outcomes.yml`
- reformatted it to use the yml structure (very similar to what you had, but now there is `:` at the end of each dictionary and sub dictionary
- Added "Topic Outcomes" for learning objectives associated with big topics (for e.g., the LO "Asses a scenario and determine the type of collision" would go under the Momentum "Topic Outcome".)
- Added "Subtopic Outcomes" for those topics that have subsubtopics (I think the "area" word was not as descriptive, so let's use topic --> subtopic --> subsubtopic

**Comment by firasm** [comment]
A couple of questions:

1. This is it for Volume 1 right?

2. I think the "Rigid Body Rotation" topic could be cleaned up a little. It seems like a mishmash of different things. I can see that the textbook organized it similarly under "fixed axis rotation" but I'm not sure I like that either.  It could also be split into two topics. I don't really have suggestions for categories at the moment, just complaints so if you can't think of anything better, let's leave it as it is.

3. Are we ready for a student to take the [OpenStax University outcomes](https://github.com/open-resources/learning_outcomes/blob/main/openstax_university.md) and populate them into the YML file?

**Comment by firasm** [comment]
And [here](https://github.com/open-resources/learning_outcomes/blob/main/Masterlist.csv) is the algorithmically generated CSV of learning outcomes that is more human readable.

**Comment by SteveCollins17** [comment]
I agree area was not very descriptive, perhaps we could do Section-->Topic --> Subtopic with Section,Topic and SubTopic Outcomes. I think Topic and SubTopic outcomes will be very similar and may be able to be combined into just simply Topic Outcomes if needed, but Section outcomes will be at a high level and deserve different terminology. So for the example "Asses a scenario and determine the type of collision" I would argue that would be a Topic Outcome of Collisions and a Section Outcome of Momentum would be more like "Recognize the definition of momentum, the units of momentum and the vector nature of momentum". Also I think it sets up the ability to give questions an identifier based on their content span a bit better (i.e. subtopic, multiple subtopics, whole topic,  multiple topics, whole section,  multiple sections). Kind of splitting hairs there, but I also think it will avoid possible confusion later when we have situations where, for example, "Force" is both a Section and a Topic.  

1) This is for Unit 1 of Volume 1, Unit 2 is only 3 chapters(SHO, waves and sound) which is covered in second term I believe. 

2) Yes I agree I don't really like the way it's organized either, I think it is organized this way partially due to the order in which sections are taught. Work is taught before Fixed Axis Rotation so Fixed Axis Rotation has a Work/Power of Rotational Motion topic which can be moved to the Work Section assuming that our master list does not need to take into account order of teaching. I will try to clean that Section up as best I can.

3) Once I clean up Rigid Body Rotation (most likely can get this done tomorrow) and we finalize how we are categorizing LOs, we will be ready for a student to assign LOs in YML file

**Comment by firasm** [comment]
Ah right, you could put that LO directly under the topic outcome of Collision.

Leave the nomenclature with me. I need to think about it a bit. The forces thing is a bit tricky. I think you already renamed the nested one "Types of Forces" perhaps to avoid this ambiguity. In general we should not have Topics and subtopics with the same names.

1. Okay, for this week just Unit 1 is fine, but eventually we will need to do the Term 2 courses as well (that is not urgent at all though).

2. Correct, we should not worry about teaching order, do a "natural ordering" instead.

3. Okay, I will assign @KafkaNoNeko (Paula) to help with this. 

P.S. The only reason I added "Subtopic outcomes" is a technical reason, so it's fine if most of those are blank (but the '-' needs to still be there to conform to YAML syntax).

**Comment by SteveCollins17** [comment]
Ok sounds good.
I will avoid topics and subtopics having the same name. Once I have the ordering cleaned up I will let you know and we can finalize how we want to do the LOs, then I can fill in Paula. It now looks like that I wont get it all cleaned up tomorrow but sometime this week for sure.

**Comment by firasm** [comment]
How’s it going on this @SteveCollins17 ?

**Comment by SteveCollins17** [comment]
Made a those few changes: Split ridged body rotation into rotational motion and rotational dynamics, moved work/power for rotational motion up to the work topic and renamed the Momentum topic to Momentum and Impulse to avoid topic/subtopic with same name. I think it is ready for Paula to populate it with LOs.

**Comment by firasm** [comment]
Thanks @SteveCollins17!

@jake-bobowski welcome to the project! Would you mind looking through the [list of topics](https://github.com/open-resources/learning_outcomes/blob/main/Masterlist_Topics_Outcomes.yml) Steve has compiled to see if things flow as you would expect?

We are not concerned about the order of teaching, but more about whether topics and subtopics fit together thematically. We will be using these Topics/Subtopics (and soon, learning outcomes) to tag each of the questions in the problem bank.

Just a quick glance to find any obvious issues is probably fine.

**Comment by jake-bobowski** [comment]
It looks very thorough!  I don't really have any comments other than it includes topics that I typically wouldn't expect to be covered in a first-year course.  The gravitation topics are covered in PHYS 216.  I personally don't cover fluids or elasticity in my first-year courses.

**Comment by firasm** [comment]
Thanks @jake-bobowski ! 

Extra topics are intentional, we'll eventually have topics and subtopics for all of the OpenStax Textbooks (vol 1-3) on here. 

Closing this issue for now, more details will be added in #3.
