### ISSUE TITLE
new LOs for center of gravity

### ISSUE THREAD

**Issue by sarajamshidn** [open-resources/learning_outcomes#36]
We need new LOs for centre of gravity. PR: https://github.com/open-resources/instructor_physics_bank/pull/1104

**Comment by muneebaashiq** [comment]
Learning outcomes were added to the question and to the list of the main list of learning outcomes.

**Comment by naclsodium** [comment]
Hi @muneebaashiq I've added the code to the question as 10.6.0.0 following the instructions in the readme file, I'm not sure if the csv file should be updated with this code?

**Comment by muneebaashiq** [comment]
Hi,

Is it possible for you to send me the link of where you have added this
change. Did you do this in a separate branch because I am unable to find
it? I believe that we do need to update the csv file but as of right now I
do not have the instructions on how to do that. Maybe we can ask about this
in the next meeting,

Kind regards,
Muneeba

**Comment by naclsodium** [comment]
Hey, Its in the pull request, I changed it to 10.6.1.0 because I realized
I forgot to add the subtopic.

**Comment by muneebaashiq** [comment]
Hi, Yes I see it I will ask Dr. Moosvi on how we can update the csv file and try to do it. Thank you

**Comment by firasm** [comment]
fixed in #47
